### Login and Store Token
POST https://joaodantas.com.br/pwserver/login
Content-Type: application/json

{
    "ownerId": "dantas",
    "ownerPwd": "mypwd"
}

###

POST https://joaodantas.com.br/pwserver/signup
Content-Type: application/json

{
  "ownerId": "dantas",
  "ownerName": "João Eduardo",
  "ownerPwd": "mypwd"
}