### Login and Store Token
POST http://localhost:8080/login
Content-Type: application/json

{
    "ownerId": "dantas",
    "ownerPwd": "mypwd"
}

###

#POST https://joaodantas.com.br/pwserver/signup
POST http://localhost:8080/signup
Content-Type: application/json

{
  "ownerId": "dantas",
  "ownerName": "João Eduardo",
  "ownerPwd": "mypwd"
}