### Login and Store Token
POST https://joaodantas.com.br/pwserver/login
Content-Type: application/json

{
  "ownerId": "dantas",
  "ownerPwd": "mypwd"
}

> {%
    client.test("Status is 200 OK", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    // Store token in global environment for subsequent calls
    client.global.set("auth_token", response.body.token);
%}

### Fetch Protected Data
GET https://joaodantas.com.br/pwserver/password/gol
Authorization: Bearer {{auth_token}}